=== bokchan/efficient-ai/bin/fourconnect/xml/RegexExpression.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" >
<element name="expressions">
	<complexType>
		<sequence>
			<element name="expression" maxOccurs="unbounded" >
				<complexType>
					<sequence>
						<element default="" name="description" type="string"></element>
						<element default="" name="pattern" type="string"></element>
						<element default="0" name="offsetY" type="int"></element>
						<element default="0" name="offsetX" type="int"></element>
						<element default="0" name="modMin" type="int"></element>
						<element default="6" name="modMax" type="int"></element>
					</sequence>
					<attribute name="enabled" type="boolean" default="true"/>
				</complexType>
			</element>
		</sequence>
	</complexType>
	</element>
</schema>

=== bokchan/efficient-ai/xml/RegexBasicMoves.xml
<?xml version="1.0" encoding="UTF-8"?>
<expressions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="RegexExpression.xsd">
  <expression>
        <description>0110</description>
        <pattern>0PP0</pattern>
        <offsetY>0</offsetY>
        <offsetX>0</offsetX>
        <modMin>0</modMin>
        <modMax>4</modMax>
    </expression>
	<expression>
        <description>1010...|.0.0</description>
        <pattern>P0P0....0.0</pattern>
        <offsetY>0</offsetY>
        <offsetX>1</offsetX>
        <modMin>0</modMin>
        <modMax>3</modMax>
    </expression>
    
	<expression>
		<description>...11.0|...1100|...00</description>
		<pattern>PP.0...PP00...00</pattern>
		<offsetY>2</offsetY>
		<offsetX>0</offsetX>
		<modMin>0</modMin>
		<modMax>3</modMax>
	</expression>
	<expression>
		<description>0.11...0011..00</description>
		<pattern>0.PP...00PP..00</pattern>
		<offsetY>2</offsetY>
		<offsetX>3</offsetX>
		<modMin>0</modMin>
		<modMax>3</modMax>
	</expression>
	<expression>
		<description>11.0...1100...10</description>
		<pattern>PP.0...PP00...P0</pattern>
		<offsetY>2</offsetY>
		<offsetX>1</offsetX>
		<modMin>0</modMin>
		<modMax>3</modMax>
	</expression>
	
	<expression>
		<description>0.11...0011..01</description>
		<pattern>0.PP...00PP..0P</pattern>
		<offsetY>2</offsetY>
		<offsetX>2</offsetX>
		<modMin>0</modMin>
		<modMax>3</modMax>
	</expression>
	
	<expression>
		<description>11.0...1100...11</description>
		<pattern>PP.0...PP00...PP</pattern>
		<offsetY>1</offsetY>
		<offsetX>2</offsetX>
		<modMin>0</modMin>
		<modMax>3</modMax>
	</expression>
	
	<expression>
		<description>0.11...0011..11</description>
		<pattern>0.PP...00PP..PP</pattern>
		<offsetY>1</offsetY>
		<offsetX>1</offsetX>
		<modMin>0</modMin>
		<modMax>3</modMax>
	</expression>
	
	<expression>
		<description>11.0...1110...11</description>
		<pattern>PP.0...PPP0...PP</pattern>
		<offsetY>2</offsetY>
		<offsetX>2</offsetX>
		<modMin>0</modMin>
		<modMax>3</modMax>
	</expression>
	
	<expression>
		<description>0.11...0111..11</description>
		<pattern>0.PP...0PPP..PP</pattern>
		<offsetY>2</offsetY>
		<offsetX>1</offsetX>
		<modMin>0</modMin>
		<modMax>3</modMax>
	</expression>
	
	<expression>
		<description>11.1...1110...11</description>
		<pattern>PP.P...PPP0...PP</pattern>
		<offsetY>0</offsetY>
		<offsetX>3</offsetX>
		<modMin>0</modMin>
		<modMax>3</modMax>
	</expression>
	
	<expression>
		<description>1.11...0111..11</description>
		<pattern>P.PP...0PPP..PP</pattern>
		<offsetY>0</offsetY>
		<offsetX>0</offsetX>
		<modMin>0</modMin>
		<modMax>3</modMax>
	</expression>
	
	<expression>
		<description>0101...0.0011.0.00...0.001</description>
		<pattern>0P0P...0.00PP.0.00...0.00P</pattern>
		<offsetY>0</offsetY>
		<offsetX>0</offsetX>
		<modMin>0</modMin>
		<modMax>1</modMax>
	</expression>
	
	<expression>
		<description>1010.1100.0...00.0..100.0</description>
		<pattern>P0P0.PP00.0...00.0..P00.0</pattern>
		<offsetY>0</offsetY>
		<offsetX>3</offsetX>
		<modMin>0</modMin>
		<modMax>1</modMax>
	</expression>
	
	
	<expression>
		<description>1101...0.0011.0.00...0.001</description>
		<pattern>PP0P...0.00PP.0.00...0.00P</pattern>
		<offsetY>0</offsetY>
		<offsetX>0</offsetX>
		<modMin>0</modMin>
		<modMax>1</modMax>
	</expression>
	
	<expression>
		<description>1011.1100.0...00.0..100.0</description>
		<pattern>P0PP.PP00.0...00.0..P00.0</pattern>
		<offsetY>0</offsetY>
		<offsetX>3</offsetX>
		<modMin>0</modMin>
		<modMax>1</modMax>
	</expression>
	
	
	<expression>
		<description>1121...0.0011.0.00...0.001</description>
		<pattern>PP[^0]P...0.00PP.0.00...0.00P</pattern>
		<offsetY>0</offsetY>
		<offsetX>2</offsetX>
		<modMin>0</modMin>
		<modMax>1</modMax>
	</expression>
	
	<expression>
		<description>1211.1100.0...00.0..100.0</description>
		<pattern>P[^0]PP.PP00.0...00.0..P00.0</pattern>
		<offsetY>0</offsetY>
		<offsetX>1</offsetX>
		<modMin>0</modMin>
		<modMax>1</modMax>
	</expression>
	
	<expression>
		<description>1121...0.0011.0.00...0.001</description>
		<pattern>PP[^0]P...0.00PP.0.00...0.00P</pattern>
		<offsetY>1</offsetY>
		<offsetX>2</offsetX>
		<modMin>0</modMin>
		<modMax>1</modMax>
	</expression>
	
	<expression>
		<description>MOVE 2.e 1211.1100.0...00.0..100.0</description>
		<pattern>P[^0]PP.PP00.0...00.0..P00.0</pattern>
		<offsetY>1</offsetY>
		<offsetX>1</offsetX>
		<modMin>0</modMin>
		<modMax>1</modMax>
	</expression>
	
	
	<expression>
		<description>MOVE 3Ra: 1[^0]1[0-2]{4}1100...0</description>
		<pattern>P[^0]P[0-2]{4}PP00...0</pattern>
		<offsetY>2</offsetY>
		<offsetX>0</offsetX>
		<modMin>0</modMin>
		<modMax>3</modMax>
	</expression>
	
	<expression>
		<description>MOVE 3La: P^0P[0-2]{3}00PP.....0</description>
		<pattern>P[^0]P[0-2]{3}00PP.....0</pattern>
		<offsetY>2</offsetY>
		<offsetX>2</offsetX>
		<modMin>1</modMin>
		<modMax>4</modMax>
	</expression>
	
	<expression>
		<description> MOVE 3Rb: 1[]^0]1[0-2]{4}1100...1</description>
		<pattern>P[^0]P[0-2]{4}PP00...100</pattern>
		<offsetY>2</offsetY>
		<offsetX>2</offsetX>
		<modMin>0</modMin>
		<modMax>3</modMax>
	</expression>
	
	<expression>
		<description>MOVE 3Lb: P^0P[0-2]{3}00PP.....0</description>
		<pattern>P[^0]P[0-2]{3}00PP...0001</pattern>
		<offsetY>2</offsetY>
		<offsetX>0</offsetX>
		<modMin>1</modMin>
		<modMax>4</modMax>
	</expression>
	
	<expression>
		<description> MOVE 3Rc: </description>
		<pattern>P[^0]P[0-2]{4}PPP[^0]...100</pattern>
		<offsetY>2</offsetY>
		<offsetX>2</offsetX>
		<modMin>0</modMin>
		<modMax>3</modMax>
	</expression>
	
	<expression>
		<description>MOVE 3Lc: P^0P[0-2]{3}00PP.....0</description>
		<pattern>P[^0]P[0-2]{3}00PPP..0001</pattern>
		<offsetY>2</offsetY>
		<offsetX>0</offsetX>
		<modMin>1</modMin>
		<modMax>4</modMax>
	</expression>
	
	<expression>
		<description> MOVE 3Rd: </description>
		<pattern>P[^0]P[0-2]{4}PPP[^0]...P00.</pattern>
		<offsetY>2</offsetY>
		<offsetX>2</offsetX>
		<modMin>0</modMin>
		<modMax>3</modMax>
	</expression>
	
	<expression>
		<description>MOVE 3Ld: </description>
		<pattern>P.P...[^0]PPP....00P</pattern>
		<offsetY>2</offsetY>
		<offsetX>0</offsetX>
		<modMin>1</modMin>
		<modMax>4</modMax>
	</expression>
	
<expression>
		<description> MOVE 3Re: </description>
		<pattern>P[^0]P[0-2]{4}PPP[^0]...P0P.</pattern>
		<offsetY>2</offsetY>
		<offsetX>1</offsetX>
		<modMin>0</modMin>
		<modMax>3</modMax>
	</expression>
	
	<expression>
		<description>MOVE 3Le: </description>
		<pattern>P.P...[^0]PPP....P0P</pattern>
		<offsetY>2</offsetY>
		<offsetX>1</offsetX>
		<modMin>1</modMin>
		<modMax>4</modMax>
	</expression>		
</expressions>

=== bokchan/efficient-ai/trunk/xml/RegexThreeInARow.xml
<?xml version="1.0" encoding="UTF-8"?>
<expressions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="RegexExpression.xsd">
  <expression enabled="true">
  	<description>Vertical</description>
    <pattern>(VAR[0-2]{6}){3}</pattern>
    <offsetY>3</offsetY>
    <offsetX>0</offsetX>
    <modMin>0</modMin>
    <modMax>6</modMax>    
  </expression>  
  <expression enabled="true">
  	<description>Horisontal 1110</description>
    <pattern>VAR{3}0{1,}</pattern>
    <offsetY>0</offsetY>
    <offsetX>3</offsetX>
    <modMin>0</modMin>
    <modMax>3</modMax>
  </expression>
  <expression enabled="true">
  	<description>Horisontal 0111</description>
    <pattern>0VAR{3}</pattern>
    <offsetY>0</offsetY>
    <offsetX>0</offsetX>
    <modMin>0</modMin>
    <modMax>3</modMax>
  </expression>
  <expression enabled="true">
  	<description>Horisontal 1101</description>
    <pattern>VARVAR0VAR</pattern>
    <offsetY>0</offsetY>
    <offsetX>2</offsetX>
    <modMin>0</modMin>
    <modMax>3</modMax>
  </expression>
  <expression enabled="true">
  	<description>Horisontal 1011</description>
    <pattern>VAR0VARVAR</pattern>
    <offsetY>0</offsetY>
    <offsetX>1</offsetX>
    <modMin>0</modMin>
    <modMax>3</modMax>
  </expression>
  <expression enabled="true">
  	<description>Diagonal increasing 1110</description>
    <pattern>(VAR[0-2]{7}){3}0</pattern>
    <offsetY>3</offsetY>
    <offsetX>3</offsetX>
    <modMin>0</modMin>
    <modMax>3</modMax>
  </expression>
  
  <expression enabled="true">
  	<description>Diagonal increasing 0111</description>
    <pattern>0[0-2]{7}(VAR[0-2]{7}){3}</pattern>
    <offsetY>0</offsetY>
    <offsetX>0</offsetX>
    <modMin>0</modMin>
    <modMax>3</modMax>
    
  </expression>
  
  <expression enabled="true">
  	<description>Diagonal increasing 1101</description>
    <pattern>(VAR[0-2]{7}){2}0[0-2]{7}VAR</pattern>
    <offsetY>2</offsetY>
    <offsetX>2</offsetX>
    <modMin>0</modMin>
    <modMax>3</modMax>
  </expression>
  
  <expression enabled="true">
  	<description>Diagonal increasing 1011</description>
    <pattern>(VAR[0-2]{7})0[0-2]{7}VAR[0-2]{7}VAR</pattern>
    <offsetY>1</offsetY>
    <offsetX>1</offsetX>
    <modMin>0</modMin>
    <modMax>3</modMax>
  </expression>
  
<expression enabled="true">
  	<description>Diagonal descreasing 1110</description>
    <pattern>(VAR[0-2]{5}){3}0</pattern>
    <offsetY>3</offsetY>
    <offsetX>-3</offsetX>
    <modMin>3</modMin>
    <modMax>6</modMax>
  </expression>
  
  <expression enabled="true">
  	<description>Diagonal descreasing 0111</description>
    <pattern>0[0-2]{5}(VAR[0-2]{5}){3}</pattern>
    <offsetY>0</offsetY>
    <offsetX>0</offsetX>
    <modMin>3</modMin>
    <modMax>6</modMax>
  </expression>
<expression enabled="true">
  	<description>Diagonal descreasing 1011</description>
    <pattern>VAR[0-2]{5}0[0-2]{5}VAR[0-2]{5}1</pattern>
    <offsetY>1</offsetY>
    <offsetX>-1</offsetX>
    <modMin>3</modMin>
    <modMax>6</modMax>
  </expression>
  <expression enabled="true">
  	<description>Diagonal descreasing 1101</description>
    <pattern>(VAR[0-2]{5}){2}0[0-2]{5}VAR</pattern>
    <offsetY>2</offsetY>
    <offsetX>-2</offsetX>
    <modMin>3</modMin>
    <modMax>6</modMax>
  </expression>    
</expressions>

=== bokchan/efficient-ai/xml/RegexThreeInARow.xml
<?xml version="1.0" encoding="UTF-8"?>
<expressions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="RegexExpression.xsd">
  <expression enabled="true">
  	<description>Vertical</description>
    <pattern>(P[0-2]{6}){3}0</pattern>
    <offsetY>3</offsetY>
    <offsetX>0</offsetX>
    <modMin>0</modMin>
    <modMax>6</modMax>    
  </expression>  
  <expression enabled="true">
  	<description>Horisontal 1110</description>
    <pattern>P{3}0{1,}</pattern>
    <offsetY>0</offsetY>
    <offsetX>3</offsetX>
    <modMin>0</modMin>
    <modMax>3</modMax>
  </expression>
  <expression enabled="true">
  	<description>Horisontal 0111</description>
    <pattern>0P{3}</pattern>
    <offsetY>0</offsetY>
    <offsetX>0</offsetX>
    <modMin>0</modMin>
    <modMax>3</modMax>
  </expression>
  <expression enabled="true">
  	<description>Horisontal 1101</description>
    <pattern>PP0P</pattern>
    <offsetY>0</offsetY>
    <offsetX>2</offsetX>
    <modMin>0</modMin>
    <modMax>3</modMax>
  </expression>
  <expression enabled="true">
  	<description>Horisontal 1011</description>
    <pattern>P0PP</pattern>
    <offsetY>0</offsetY>
    <offsetX>1</offsetX>
    <modMin>0</modMin>
    <modMax>3</modMax>
  </expression>
  <expression enabled="true">
  	<description>Diagonal increasing 1110</description>
    <pattern>(P[0-2]{7}){2}P[^0]</pattern>
    <offsetY>3</offsetY>
    <offsetX>3</offsetX>
    <modMin>0</modMin>
    <modMax>3</modMax>
  </expression>
  
  <expression enabled="true">
  	<description>Diagonal inscreasing1 0111, Must precede</description>
    <pattern>[^0][0-2]{7}0[0-2]{7}(P[0-2]{7}){3}</pattern>
    <offsetY>1</offsetY>
    <offsetX>0</offsetX>
    <modMin>3</modMin>
    <modMax>6</modMax>
  </expression>
  
  <expression enabled="true">
  	<description>Diagonal increasing 0111</description>
    <pattern>0[0-2]{7}(P[0-2]{7}){3}</pattern>
    <offsetY>0</offsetY>
    <offsetX>0</offsetX>
    <modMin>0</modMin>
    <modMax>3</modMax>
  </expression>
  
  <expression enabled="true">
  	<description>Diagonal increasing 1101</description>
    <pattern>P[0-2]{7}P[^0][0-2]{6}0[0-2]{7}P</pattern>
    <offsetY>2</offsetY>
    <offsetX>2</offsetX>
    <modMin>0</modMin>
    <modMax>3</modMax>
  </expression>
  
  <expression enabled="true">
  	<description>Diagonal increasing 1011</description>
    <pattern>(P[^0][0-2]{6})0[0-2]{7}P[0-2]{7}P</pattern>
    <offsetY>1</offsetY>
    <offsetX>1</offsetX>
    <modMin>0</modMin>
    <modMax>3</modMax>
  </expression>
  
<expression enabled="true">
  	<description>Diagonal descreasing 1110</description>
    <pattern>P[0-2]{5}P[0-2]{4}[^0]P</pattern>
    <offsetY>3</offsetY>
    <offsetX>-3</offsetX>
    <modMin>3</modMin>
    <modMax>6</modMax>
  </expression>
    
	<expression enabled="true">
  	<description>Diagonal descreasing1 0111, Must precede </description>
    <pattern>[^0][0-2]{6}0[0-2]{5}(P[0-2]{5}){3}</pattern>
    <offsetY>0</offsetY>
    <offsetX>0</offsetX>
    <modMin>3</modMin>
    <modMax>6</modMax>
  </expression>
	
  <expression enabled="true">
  	<description>Diagonal descreasing2 0111</description>
    <pattern>0([0-2]{5}P){3}</pattern>
    <offsetY>0</offsetY>
    <offsetX>0</offsetX>
    <modMin>3</modMin>
    <modMax>6</modMax>
  </expression>
<expression enabled="true">
  	<description>Diagonal descreasing 1011</description>
    <pattern>[^0]P[0-2]{5}0[0-2]{5}P[0-2]{5}1</pattern>
    <offsetY>1</offsetY>
    <offsetX>0</offsetX>
    <modMin>3</modMin>
    <modMax>6</modMax>
  </expression>
  <expression enabled="true">
  	<description>Diagonal descreasing 1101</description>
    <pattern>(P[0-2]{4})[^0]P[0-2]{5}{2}0[0-2]{5}P</pattern>
    <offsetY>2</offsetY>
    <offsetX>-2</offsetX>
    <modMin>3</modMin>
    <modMax>6</modMax>
  </expression>
  
  <expression>
        <description>(1[^0]{2}1[0-2]{3}){2}0100</description>
        <pattern>(P[^0]{2}P[0-2]{3}){2}0P00</pattern>
        <offsetY>2</offsetY>
        <offsetX>0</offsetX>
        <modMin>0</modMin>
        <modMax>3</modMax>
    </expression>    
</expressions>

=== bokchan/efficient-ai/bin/fourconnect/xml/RegexKillerMovesMinimal.xml
<?xml version="1.0" encoding="UTF-8"?>
<expressions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="RegexExpression.xsd">
<expression>
        <description>x1100xx11100xx</description>
        <pattern>PP00..PPP</pattern>
        <offsetY>0</offsetY>
        <offsetX>2</offsetX>
        <modMin>1</modMin>
        <modMax>3</modMax>
    </expression>
    <expression>
        <description>x1011xx1101xxx</description>
        <pattern>P0PP..PP0P</pattern>
        <offsetY>0</offsetY>
        <offsetX>1</offsetX>
        <modMin>1</modMin>
        <modMax>3</modMax>
    </expression>
    <expression>
        <description>xx0011xxx00111</description>
        <pattern>PP...00PPP</pattern>
        <offsetY>0</offsetY>
        <offsetX>1</offsetX>
        <modMin>0</modMin>
        <modMax>2</modMax>
    </expression>
    <expression>
        <description>x1011xx1101xxx</description>
        <pattern>P0PP..PP0P</pattern>
        <offsetY>0</offsetY>
        <offsetX>1</offsetX>
        <modMin>1</modMin>
        <modMax>3</modMax>
    </expression>
    <expression>
        <description>xx1010x1110x0x</description>
        <pattern>P0P0.PPP0.0</pattern>
        <offsetY>0</offsetY>
        <offsetX>1</offsetX>
        <modMin>3</modMin>
        <modMax>4</modMax>
    </expression>
    <expression>
        <description>xx1010xx11010x</description>
        <pattern>P0P0..PP0P0</pattern>
        <offsetY>0</offsetY>
        <offsetX>1</offsetX>
        <modMin>1</modMin>
        <modMax>3</modMax>
    </expression>
    <expression>
        <description>xxx0110xx10110</description>
        <pattern>0PP0..P0PP0</pattern>
        <offsetY>0</offsetY>
        <offsetX>0</offsetX>
        <modMin>1</modMin>
        <modMax>3</modMax>
    </expression>
    <expression>
        <description>xx1010xx11010x</description>
        <pattern>P0P0..PP0P0</pattern>
        <offsetY>0</offsetY>
        <offsetX>1</offsetX>
        <modMin>1</modMin>
        <modMax>3</modMax>
    </expression>
    <expression>
        <description>xx1101xxx1101x</description>
        <pattern>PP0P...PP0P</pattern>
        <offsetY>0</offsetY>
        <offsetX>2</offsetX>
        <modMin>0</modMin>
        <modMax>3</modMax>
    </expression>
    <expression>
        <description>x1011xxx1011xx</description>
        <pattern>P0PP...P0PP</pattern>
        <offsetY>0</offsetY>
        <offsetX>1</offsetX>
        <modMin>0</modMin>
        <modMax>3</modMax>
    </expression>
    <expression>
        <description>x0101xxx01011x</description>
        <pattern>0P0P...0P0PP</pattern>
        <offsetY>0</offsetY>
        <offsetX>0</offsetX>
        <modMin>0</modMin>
        <modMax>2</modMax>
    </expression>
    <expression>
        <description>x0101xxx01011x</description>
        <pattern>0P0P...0P0PP</pattern>
        <offsetY>0</offsetY>
        <offsetX>0</offsetX>
        <modMin>0</modMin>
        <modMax>2</modMax>
    </expression>
    <expression>
        <description>xx1101xxxx1011</description>
        <pattern>PP0P....P0PP</pattern>
        <offsetY>0</offsetY>
        <offsetX>2</offsetX>
        <modMin>0</modMin>
        <modMax>2</modMax>
    </expression>
    <expression>
        <description>x0101xxx0x0111</description>
        <pattern>0P0P...0.0PPP</pattern>
        <offsetY>0</offsetY>
        <offsetX>0</offsetX>
        <modMin>0</modMin>
        <modMax>1</modMax>
    </expression>
    <expression>
        <description>xxx0xxxx1101xxx1x0xxx</description>
        <pattern>0....PP0P...P.0</pattern>
        <offsetY>0</offsetY>
        <offsetX>0</offsetX>
        <modMin>2</modMin>
        <modMax>5</modMax>
    </expression>
    <expression>
        <description>xxxxxx1xxx0x1xxxx0111xxx0xxx</description>
        <pattern>P...0.P....0PPP</pattern>
        <offsetY>1</offsetY>
        <offsetX>-3</offsetX>
        <modMin>3</modMin>
        <modMax>6</modMax>
    </expression>
    <expression>
        <description>xx1101xxxx1011</description>
        <pattern>PP0P[0-2]{4}P0PP</pattern>
        <offsetY>0</offsetY>
        <offsetX>2</offsetX>
        <modMin>0</modMin>
        <modMax>2</modMax>
    </expression>
    <expression>
        <description>xxxxx0xxxx1101xxx1101</description>
        <pattern>0....PP0P...PP0P</pattern>
        <offsetY>0</offsetY>
        <offsetX>0</offsetX>
        <modMin>2</modMin>
        <modMax>5</modMax>
    </expression>
    <expression>
        <description>xxxxx1xxxxxx1xxxx1100</description>
        <pattern>P......P....PP00</pattern>
        <offsetY>2</offsetY>
        <offsetX>0</offsetX>
        <modMin>2</modMin>
        <modMax>5</modMax>
    </expression>
    <expression>
        <description>x0110xx10110xx</description>
        <pattern>0PP0[0-2]{2}P0PP0</pattern>
        <offsetY>0</offsetY>
        <offsetX>0</offsetX>
        <modMin>1</modMin>
        <modMax>3</modMax>
    </expression>
    <expression>
        <description>xx0110xxx01101</description>
        <pattern>0PP0[0-2]{3}0PP0P</pattern>
        <offsetY>0</offsetY>
        <offsetX>0</offsetX>
        <modMin>0</modMin>
        <modMax>3</modMax>
    </expression>
    <expression>
        <description>xx101xxx1101xxx1101xx</description>
        <pattern>P0P...PP0P...PP0P</pattern>
        <offsetY>0</offsetY>
        <offsetX>1</offsetX>
        <modMin>1</modMin>
        <modMax>4</modMax>
    </expression>
    <expression>
        <description>x0xxxxx1011xxx1011xxx</description>
        <pattern>0.....P0PP...P0PP</pattern>
        <offsetY>0</offsetY>
        <offsetX>0</offsetX>
        <modMin>1</modMin>
        <modMax>3</modMax>
    </expression>
    <expression>
        <description>x1xxxxxx1xxxxx0011xxx</description>
        <pattern>P......P.....00PP</pattern>
        <offsetY>2</offsetY>
        <offsetX>0</offsetX>
        <modMin>1</modMin>
        <modMax>4</modMax>
    </expression>
    <expression>
        <description>xxx0xxxxx1011x1110xxx</description>
        <pattern>0[0-2]{5}P0PP.PPP0</pattern>
        <offsetY>0</offsetY>
        <offsetX>0</offsetX>
        <modMin>3</modMin>
        <modMax>4</modMax>
    </expression>
    <expression>
        <description>xxx0xxxx1101xxxxx0111</description>
        <pattern>0PPP.PP0P[0-2]{5}0</pattern>
        <offsetY>0</offsetY>
        <offsetX>0</offsetX>
        <modMin>2</modMin>
        <modMax>3</modMax>
    </expression>
    <expression>
        <description>1xxxxxxx1x0xxx1110xxxxxx0xxx</description>
        <pattern>P.......P.0...PPP0</pattern>
        <offsetY>1</offsetY>
        <offsetX>3</offsetX>
        <modMin>0</modMin>
        <modMax>3</modMax>
    </expression>
    <expression>
        <description>xxxxx1xxx0x1xxxx0111xxx0xxxx</description>
        <pattern>P...0.P....0PPP...0</pattern>
        <offsetY>1</offsetY>
        <offsetX>-3</offsetX>
        <modMin>3</modMin>
        <modMax>6</modMax>
    </expression>
    <expression>
        <description>xxx1100xx11100xxxxx00</description>
        <pattern>PP00..PPP00[0-2]{5}00</pattern>
        <offsetY>0</offsetY>
        <offsetX>2</offsetX>
        <modMin>1</modMin>
        <modMax>3</modMax>
    </expression>
    <expression>
        <description>0011xxx00111xx00xxxxx</description>
        <pattern>00PP[0-2]{3}00PPP..00</pattern>
        <offsetY>0</offsetY>
        <offsetX>1</offsetX>
        <modMin>0</modMin>
        <modMax>2</modMax>
    </expression>
    <expression>
        <description>xxx1101xxx1101</description>
        <pattern>PP0P{P,}[0-2]{2,}PP0P</pattern>
        <offsetY>0</offsetY>
        <offsetX>2</offsetX>
        <modMin>0</modMin>
        <modMax>3</modMax>
    </expression>
    <expression>
        <description>xxx1xxxxx1xxxx0011xxx</description>
        <pattern>P[0-2]{5}P[0-2]{4}00PP</pattern>
        <offsetY>2</offsetY>
        <offsetX>-2</offsetX>
        <modMin>3</modMin>
        <modMax>6</modMax>
    </expression>

    </expressions>

=== bokchan/efficient-ai/trunk/xml/RegexFourInARow.xml
<?xml version="1.0" encoding="UTF-8"?>
<expressions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="RegexExpression.xsd">
  <expression>
    <description>Vertical</description>
    <pattern>(VAR{1}[0-2]{6}){4}</pattern>
    <offsetY>4</offsetY>
    <offsetX>0</offsetX>
    <modMin>0</modMin>
    <modMax>6</modMax>
  </expression>
  <expression>
    <description>Horizontal</description>
    <pattern>VAR{4}</pattern>
    <offsetY>0</offsetY>
    <offsetX>0</offsetX>
    <modMin>0</modMin>
    <modMax>3</modMax>
  </expression>
    <expression>
    <description>Diagonal increasing</description>
    <pattern>(VAR{1}[0-2]{7}){4,}</pattern>
    <offsetY>4</offsetY>
    <offsetX>4</offsetX>
    <modMin>0</modMin>
    <modMax>3</modMax>
  </expression>
  <expression>
    <description>Diagonal decreasing</description>
    <pattern>(VAR{1}[0-2]{5}){4,}</pattern>
    <offsetY>4</offsetY>
    <offsetX>-4</offsetX>
    <modMin>3</modMin>
    <modMax>6</modMax>
  </expression>
</expressions>
